/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkkp;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author ROYAN FARID
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        setSize(400,200);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocation(0, 0);
        getContentPane().setBackground(new java.awt.Color(250, 234, 72));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnPeserta = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenuItem();
        mnKabKota = new javax.swing.JMenuItem();
        mnKec = new javax.swing.JMenuItem();
        mnKel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAdministrasi = new javax.swing.JMenuItem();
        mnsNilai = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        popupMenu1.setLabel("popupMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(250, 234, 72));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 55)); // NOI18N
        jLabel1.setText("MAIN MENU");

        jLabel2.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        jLabel2.setText("* this view can only be seen by Admin");

        jMenu1.setText("MASTER");

        mnPeserta.setText("Input Participant");
        mnPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPesertaActionPerformed(evt);
            }
        });
        jMenu1.add(mnPeserta);

        mnUser.setText("Input Admin");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        jMenu1.add(mnUser);

        mnKabKota.setText("Recent Regencies");
        mnKabKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKabKotaActionPerformed(evt);
            }
        });
        jMenu1.add(mnKabKota);

        mnKec.setText("Recent Districts");
        mnKec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKecActionPerformed(evt);
            }
        });
        jMenu1.add(mnKec);

        mnKel.setText("Recent Villages");
        mnKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKelActionPerformed(evt);
            }
        });
        jMenu1.add(mnKel);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("TRANSACTION");

        mnAdministrasi.setText("Administration Selection");
        mnAdministrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdministrasiActionPerformed(evt);
            }
        });
        jMenu2.add(mnAdministrasi);

        mnsNilai.setText("Grades Selection");
        mnsNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsNilaiActionPerformed(evt);
            }
        });
        jMenu2.add(mnsNilai);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("REPORT");

        jMenuItem10.setText("Participant Data");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Admin Data");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Pass Adminstrative Selection");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem1.setText("Pass Grades Selection");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem14.setText("Final Participant Report");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("UTILITY");

        jMenuItem3.setText("About Developer");
        jMenu4.add(jMenuItem3);

        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKabKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKabKotaActionPerformed
        // TODO add your handling code here:
        new frmKabKota().setVisible(true);
    }//GEN-LAST:event_mnKabKotaActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        // TODO add your handling code here:
        new frmUser().setVisible(true);
    }//GEN-LAST:event_mnUserActionPerformed

    private void mnPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPesertaActionPerformed
        // TODO add your handling code here:
        new frmPeserta().setVisible(true);
    }//GEN-LAST:event_mnPesertaActionPerformed

    private void mnKecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKecActionPerformed
        // TODO add your handling code here:
        new frmKecamatan().setVisible(true);
    }//GEN-LAST:event_mnKecActionPerformed

    private void mnKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKelActionPerformed
        // TODO add your handling code here:
        new frmKelurahan().setVisible(true);
    }//GEN-LAST:event_mnKelActionPerformed

    private void mnAdministrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdministrasiActionPerformed
        // TODO add your handling code here:
        new frmSeleksiAdm().setVisible(true);
    }//GEN-LAST:event_mnAdministrasiActionPerformed

    private void mnsNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsNilaiActionPerformed
        // TODO add your handling code here:
        new frmSeleksiNilai().setVisible(true);
    }//GEN-LAST:event_mnsNilaiActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    java.lang.System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new frmSelectPeserta().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new frmDataUser().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new frmSelectLolosAdm().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new frmLolosSeleksiNilai().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new frmLolosFinal().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenuItem mnAdministrasi;
    private javax.swing.JMenuItem mnKabKota;
    private javax.swing.JMenuItem mnKec;
    private javax.swing.JMenuItem mnKel;
    private javax.swing.JMenuItem mnPeserta;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JMenuItem mnsNilai;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
